export const LOSTPETSINFO_LOADING = 'LOSTPETSINFO_LOADING';
export const LOSTPETSINFO_FAILED = 'LOSTPETSINFO_FAILED';
export const ADD_LOSTPETSINFO = 'ADD_LOSTPETSINFO';
export const ADD_LOSTPET = 'ADD_LOSTPET';

export const ADD_PETFORADOPTION = 'ADD_PETFORADOPTION';
export const PETSFORADOPTIONINFO_LOADING = 'PETSFORADOPTIONINFO_LOADING';
export const ADD_PETSFORADOPTIONINFO = 'ADD_PETSFORADOPTIONINFO';
export const PETSFORADOPTIONINFO_FAILED = 'PETSFORADOPTIONINFO_FAILED';