export const LOSTPETSINFO_LOADING = 'LOSTPETSINFO_LOADING';
export const LOSTPETSINFO_FAILED = 'LOSTPETSINFO_FAILED';
export const ADD_LOSTPETSINFO = 'ADD_LOSTPETSINFO';
export const ADD_LOSTPET = 'ADD_LOSTPET';